# Automatically approve pull requests for files in the Scrapes directory.

name: Automatically approve scraper pull requests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changed files
        id: changes
        run: |
          files=$(git diff --name-only ${{ github.base_ref }}...HEAD)
          echo "$files"
          echo "$files" | grep -vE '^Scrapes/' && echo "non-scrapes-changes=true" >> $GITHUB_OUTPUT || echo "non-scrapes-changes=false" >> $GITHUB_OUTPUT

      - name: Auto approve
        if: steps.changes.outputs.non-scrapes-changes == 'false'
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
